--
- name: playbook_1
  hosts: all
  vars:
   a: "this is laptop"
   b: "this is second laptop"
  tasks:
   -  name: task_1
      debug:
        msg: "{{a}}"
   -  name: task_2
      debug:
       msg: "{{b}}"
...
